=== Braayy/PowerNukkit-Universal-Converters/src/main/resources/org/powernukkit/universal/block/universal-block-properties.dtd
<!--
  -     PowerNukkit Universal Worlds & Converters for Minecraft
  -     Copyright (C) 2020  José Roberto de Araújo Júnior
  -
  -     This program is free software: you can redistribute it and/or modify
  -     it under the terms of the GNU Affero General Public License as published by
  -     the Free Software Foundation, either version 3 of the License, or
  -     (at your option) any later version.
  -
  -     This program is distributed in the hope that it will be useful,
  -     but WITHOUT ANY WARRANTY; without even the implied warranty of
  -     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  -     GNU Affero General Public License for more details.
  -
  -     You should have received a copy of the GNU Affero General Public License
  -     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!ELEMENT int-rage EMPTY>
<!ATTLIST int-rage
        from    CDATA   "0"
        to      CDATA   #REQUIRED>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
        default CDATA       #IMPLIED
        java    NMTOKEN     #IMPLIED
        bedrock NMTOKEN     #IMPLIED>

<!ELEMENT boolean EMPTY>
<!ATTLIST boolean
        default       (true|false)  "false"
        java-false    NMTOKEN     'false'
        bedrock-false NMTOKEN     '0'
        java-true     NMTOKEN     'true'
        bedrock-true  NMTOKEN     '1'>

<!ELEMENT block-property (int-rage|boolean|value+)>
<!ATTLIST block-property
        id      ID          #REQUIRED
        java    NMTOKEN     #IMPLIED
        bedrock NMTOKEN     #IMPLIED
        java-requires-adapter       (true|false) "false"
        bedrock-requires-adapter    (true|false) "false">

<!ELEMENT block-properties (block-property+)>

<!ELEMENT use-property EMPTY>
<!ATTLIST use-property id   IDREF   #REQUIRED>


<!ELEMENT block-type (use-property*)>
<!ATTLIST block-type
        id      ID          #REQUIRED
        java    NMTOKEN     #IMPLIED
        bedrock NMTOKEN     #IMPLIED>

<!ELEMENT block-types (block-type+)>

=== Braayy/PowerNukkit-Universal-Converters/src/main/resources/org/powernukkit/universal/block/universal-block-properties.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~     PowerNukkit Universal Worlds & Converters for Minecraft
  ~     Copyright (C) 2020  José Roberto de Araújo Júnior
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU Affero General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU Affero General Public License for more details.
  ~
  ~     You should have received a copy of the GNU Affero General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!DOCTYPE block-properties SYSTEM "universal-block-properties.dtd">
<block-properties>
    <block-property id="age1" java-requires-adapter="true" bedrock-requires-adapter="true">
        <boolean java-false="0" java-true="1" />
    </block-property>
    <block-property id="age2" java-requires-adapter="true" bedrock-requires-adapter="true">
        <int-rage to="2"/>
    </block-property>
    <block-property id="age3" java-requires-adapter="true" bedrock-requires-adapter="true">
        <int-rage to="3"/>
    </block-property>
    <block-property id="age5" java-requires-adapter="true" bedrock-requires-adapter="true">
        <int-rage to="5"/>
    </block-property>
    <block-property id="age7" java-requires-adapter="true" bedrock-requires-adapter="true">
        <int-rage to="7"/>
    </block-property>
    <block-property id="age15" java-requires-adapter="true" bedrock-requires-adapter="true">
        <int-rage to="15"/>
    </block-property>
    <block-property id="age25" java-requires-adapter="true" bedrock-requires-adapter="true">
        <int-rage to="25"/>
    </block-property>
    <block-property id="allow_underwater" bedrock="allow_underwater_bit" java-requires-adapter="true">
        <boolean/>
    </block-property>
    <block-property id="attached" bedrock="attached_bit">
        <boolean/>
    </block-property>
    <block-property id="attachment">
        <value java="floor" default="true">standing</value>
        <value java="ceiling">hanging</value>
        <value java="single_wall">side</value>
        <value java="double_wall">multiple</value>
    </block-property>
    <block-property id="leaves">
        <value bedrock="no_leaves" default="true">none</value>
        <value bedrock="small_leaves">small</value>
        <value bedrock="large_leaves">large</value>
    </block-property>
    <block-property id="bamboo_stalk_thickness" java-requires-adapter="true">
        <value java="0">thin</value>
        <value java="1">thick</value>
    </block-property>
    <block-property id="bites" bedrock="bite_counter">
        <int-rage to="6"/>
    </block-property>
    <block-property id="block_light_level" java-requires-adapter="true">
        <int-rage to="15"/>
    </block-property>
    <block-property id="brewing_stand_slot_a" bedrock="brewing_stand_slot_a_bit" java="has_bottle_0">
        <boolean/>
    </block-property>
    <block-property id="brewing_stand_slot_b" bedrock="brewing_stand_slot_b_bit" java="has_bottle_1">
        <boolean/>
    </block-property>
    <block-property id="brewing_stand_slot_c" bedrock="brewing_stand_slot_c_bit" java="has_bottle_2">
        <boolean/>
    </block-property>
    <block-property id="powered" bedrock="powered_bit">
        <boolean/>
    </block-property>
    <block-property id="face" bedrock-requires-adapter="true">
        <value>celling</value>
        <value>floor</value>
        <value>wall</value>
    </block-property>
    <block-property id="horizontal_direction" bedrock="direction" java="facing">
        <value bedrock="0" default="true">south</value>
        <value bedrock="1">west</value>
        <value bedrock="2">north</value>
        <value bedrock="3">east</value>
    </block-property>
    <block-property id="stairs_direction" bedrock="weirdo_direction" java="facing">
        <value bedrock="0" default="true">east</value>
        <value bedrock="1">west</value>
        <value bedrock="2">south</value>
        <value bedrock="3">north</value>
    </block-property>
    <block-property id="facing_direction" java="facing">
        <value bedrock="0" default="true">down</value>
        <value bedrock="1">up</value>
        <value bedrock="2">north</value>
        <value bedrock="3">south</value>
        <value bedrock="4">west</value>
        <value bedrock="5">east</value>
    </block-property>
    <block-property id="hopper_direction" java="facing">
        <value bedrock="0" default="true">down</value>
        <value bedrock="2">north</value>
        <value bedrock="3">south</value>
        <value bedrock="4">west</value>
        <value bedrock="5">east</value>
    </block-property>
    <block-property id="cauldron_liquid" java-requires-adapter="true">
        <value default="true">water</value>
        <value>lava</value>
    </block-property>
    <block-property id="chemistry_table_type" java-requires-adapter="true">
        <value>compound_creator</value>
        <value>material_reducer</value>
        <value>element_constructor</value>
        <value>lab_table</value>
    </block-property>
    <block-property id="wood_type">
        <value>acacia</value>
        <value>birch</value>
        <value>dark_oak</value>
        <value>jungle</value>
        <value>oak</value>
        <value>spruce</value>
    </block-property>
</block-properties>
